### ISSUE TITLE
Integrate EasyJSON for Faster JSON Parsing

### ISSUE THREAD

**Issue by Jalmeida1994** [inbox451/inbox451#11]
Integrate [easyjson](https://github.com/zerodha/easyjson) to improve JSON parsing performance by generating marshaling/unmarshaling code at compile time instead of using reflection.

**Comment by Jalmeida1994** [comment]
Perhaps we should hold off on this as it feels like we're optimizing for performance too early. Maybe we can revisit this in the future when we see the need for a performance boost. Also, it seems [EasyJSON's original repo](https://github.com/mailru/easyjson) is no longer actively maintained.

What do you think @lmmendes?

**Comment by lmmendes** [comment]
I agree, let's wait until we have the first release is out the door, and when that happens we should have a better understanding of the Golang ecosystem and can revisit this issue.
